nsc-events-nestjs-7-118-refactor-getAllActivities-service-method
SeattleColleges/nsc-events-nestjs pull request #119
Opened 2024-05-23 21:53 UTC by cshimm

This pull request updates the getAllActivities service method and controller by removing the numEvents parameter, adding two filter options for isArchived and isHidden, and adding sort by _id option. Adding `_id: 1` as a secondary sort ensures a consistent and predictable order, especially when multiple documents have the same eventDate.

From the front-end code a page number can be passed as a query parameter and a small chunk of events (default 5) will be returned. This chunk size can also be configured by passing in a numEvents query parameter from the front end. 

Filter logic:
If the query includes isArchived or isHidden, add an $or condition to the filter.
This $or condition ensures that the filter will match documents where either isArchived is true or isHidden is true (or both).
Specifically:
If isArchived is provided, add it to the list of conditions.
If isHidden is provided, add it to the list of conditions.
The result is a filter that will find events that are either archived, hidden, or both, depending on what parameters are passed in the query.

This returns the first 5 event where isArchived is true:
![image](https://github.com/SeattleColleges/nsc-events-nestjs/assets/13278479/d144e614-39b4-4da8-ba1f-8d45454e0334)

This returns the first 5 events where isArchived **or** isHidden is true:
![image](https://github.com/SeattleColleges/nsc-events-nestjs/assets/13278479/e4a77b30-c9a9-4cab-a39e-bf5ac2f663a8)

This returns the first 5 events active events (isArchive and isHidden are false):
![image](https://github.com/SeattleColleges/nsc-events-nestjs/assets/13278479/0aec5315-209d-40cc-88b1-d4da061b1601)

You can also mix and match, say if you wanted to return a mix of events where isArchived is false or isHidden is true. To do this however, you'll need to specify values for both isArchived and isHidden instead of omitting the param you want values to be be false for:
![image](https://github.com/SeattleColleges/nsc-events-nestjs/assets/13278479/06e135f9-6787-496a-8633-efd4471bc17c)

Tests for the getAllActivities controller and service method were also updated to reflect these changes.

2024-05-24 05:18 UTC, Ali-7s approved these changes
LGTM!

All of the filters work well for me
<img width="871" alt="image" src="https://github.com/SeattleColleges/nsc-events-nestjs/assets/22021615/15a88eec-be2a-437d-958d-af2c5283afdd">

2024-05-26 20:52 UTC, taylorpapke approved these changes
Looks good to me:
<img width="837" alt="Screenshot 2024-05-26 at 1 48 10 PM" src="https://github.com/SeattleColleges/nsc-events-nestjs/assets/94101953/a0096caa-e455-41c9-8f69-747e17267bd1">
<img width="841" alt="Screenshot 2024-05-26 at 1 48 44 PM" src="https://github.com/SeattleColleges/nsc-events-nestjs/assets/94101953/5e6469dd-95de-40aa-8c57-9badaefb5150">
<img width="829" alt="Screenshot 2024-05-26 at 1 49 25 PM" src="https://github.com/SeattleColleges/nsc-events-nestjs/assets/94101953/f572ce83-35f1-4696-aea3-626145607a4d">
<img width="835" alt="Screenshot 2024-05-26 at 1 50 41 PM" src="https://github.com/SeattleColleges/nsc-events-nestjs/assets/94101953/4dc4c586-b823-4164-8225-482345d91f26">

2024-05-27 06:38 UTC, heosman requested changes
The filtering works for only certain cases on my end.

Works when:
Filtering by isHidden=true or IsArchived=true or both.

Doesn't work when:
I set =?page=1 (first 5 events are displayed, including archived and hidden events):
<img width="518" alt="image" src="https://github.com/SeattleColleges/nsc-events-nestjs/assets/77591083/413aabf3-af81-41b9-8cd5-0cdbd954ead4">

Filtering with both isHidden=false AND IsArchived=false (first 5 events are displayed, including archived and hidden events):
<img width="518" alt="image" src="https://github.com/SeattleColleges/nsc-events-nestjs/assets/77591083/a0e00d34-7189-4e59-8131-4ab745da7782">

2024-05-27 06:47 UTC, intisarosman1 reviewed
The filter works for hidden/archived items
![Screenshot 2024-05-26 231058](https://github.com/SeattleColleges/nsc-events-nestjs/assets/77607212/405a274d-b6e9-41c5-8417-a8cf948fdade)

but I'm having the same issue as @heosman 
![Screenshot 2024-05-26 234037](https://github.com/SeattleColleges/nsc-events-nestjs/assets/77607212/ceff9c42-2cf0-4ab2-91c6-9bd4273e1c20)

2024-05-27 17:35 UTC, brinkbrink commented
Thank you for always being so thorough with your reviews, @heosman! If anybody is ever looking to improve their PR reviews, take a look at what @heosman does. Of course some of her requested changes will be related to her role as PO/TPM of NSC Events but a lot of it could be mirrored by any team member, like with this review here.

2024-05-27 18:32 UTC, cshimm commented
@intisarosman1 @heosman  Thank you both for the feedback! I've made some changes that fix the archived events being returned when isArchived and isHidden params are omitted, now only active events will be returned. Omitting either of the parameters will be treated the same as explicitly passing false into the query.

How should I approach the case where the isArchived param is true and isHidden param is true? 
I could handle that case in 2 ways: return event where **_either_** isArchived is true or isHidden is true. This means some events will be returned where the event's isArchived is false or isHidden is false if the corresponding isArchived or isHidden is true. This might be confusing since the query specifies both to be true.

The other case is returning events where _**both**_ the isArchived and is isHidden key is true.

2024-05-28 00:04 UTC, heosman approved these changes
With the new changes, filtering by ?page=1 and &isArchived=false&isHidden=false now only display active events. Good work!

2024-05-28 00:05 UTC, merged