nsc-events-nextjs_11_141_upgrade-packages
SeattleColleges/nsc-events-nestjs pull request #142
Opened 2024-08-13 02:21 UTC by Alzavio

Resolves 151, upgrading the packages in the repo

2024-08-18 08:05 UTC, theGaryLarson requested changes
hey @Alzavio I just saw this sorry busy with work and didn't realize I was being asked to review. 

I'd try to do updates in smaller batches in case things break but if you can get the following resolved and CI runs you are probably okay to roll with it. See details below

One of the reasons the CI is failing is because it is set to use Node 18. The update to Node 22 requires changes to the following yml file `.github/workflows/ci.yml starting on Line 18` The build and test job. You can review closed pull request #17 to see the changes there. You may want to look into how to store the artifact for the build as well. (Also part of that pull request. You can review under the commits there. @bcko Hope this helps :)

2024-08-18 08:18 UTC, theGaryLarson commented on package.json
> -    "node": "18.x"
@Alzavio I believe this change right here is what is causing the package.lock.json error. When the workflow runs npm ci iirc it references this for which node version. I could be wrong though been awhile since I looked over these things.

2024-08-18 08:46 UTC, theGaryLarson requested changes

2024-08-18 08:46 UTC, theGaryLarson commented on package.json
> +    "mongoose": "^8.5.3",
Major version update. May be best not to include this until you can identify the breaking changes being introduced. See Semantic Versioning breakdown in main comment.

2024-08-18 08:46 UTC, theGaryLarson commented on package.json
> +    "@typescript-eslint/eslint-plugin": "^8.1.0",
Major version update. May be best not to include this until you can identify the breaking changes being introduced. See Semantic Versioning breakdown in main comment.

2024-08-18 08:46 UTC, theGaryLarson commented on package.json
> +    "eslint-config-prettier": "^9.1.0",
Major version update. May be best not to include this until you can identify the breaking changes being introduced. See Semantic Versioning breakdown in main comment.

2024-08-18 08:46 UTC, theGaryLarson commented on package.json
> +    "eslint-plugin-prettier": "^5.2.1",
Major version update. May be best not to include this until you can identify the breaking changes being introduced. See Semantic Versioning breakdown in main comment.

2024-08-18 08:46 UTC, theGaryLarson commented on package.json
> +    "prettier": "3.3.3",
Major version update. May be best not to include this until you can identify the breaking changes being introduced. See Semantic Versioning breakdown in main comment.

2024-08-18 08:46 UTC, theGaryLarson commented on package.json
> +    "supertest": "^7.0.0",
Major version update. May be best not to include this until you can identify the breaking changes being introduced. See Semantic Versioning breakdown in main comment.

2024-08-18 08:46 UTC, theGaryLarson commented on package.json
> +    "@types/passport-jwt": "^4.0.1",
Major version update. May be best not to include this until you can identify the breaking changes being introduced. See Semantic Versioning breakdown in main comment. I believe this is for our auth. So may be required if there are vulnerabilities in the old package and may be a priority to look into first.

2024-08-18 08:46 UTC, theGaryLarson commented on package.json
> +    "@types/node": "^22.3.0",
Major version update. May be best not to include this until you can identify the breaking changes being introduced. See Semantic Versioning breakdown in main comment.

2024-08-18 08:46 UTC, theGaryLarson commented on package-lock.json
If this is being deleted. In the yml file mentioned in the main comment you may need to run `npm i` rather than `npm ci`.

2024-09-27 22:04 UTC, JesseCaddell commented
Closing PR for now, will request more developers to trouble shoot in next sprint. Package updates will become part of our sprint cycles.

2024-09-27 22:04 UTC, closed without merging