nsc-events-nestjs_1_29_createuserdto
SeattleColleges/nsc-events-nestjs pull request #30
Opened 2023-10-09 01:46 UTC by Ali-7s

Resolves #29 

This PR adds the CreateUserDto class with validation.

2023-10-09 16:54 UTC, Seiyaroo submitted a review, later dismissed
LGTM, no major changes needed :)

2023-10-09 23:52 UTC, Exochos commented
lgtm

2023-10-11 00:29 UTC, theGaryLarson requested changes
Overall looks good. Do not include password in this dto. Even though it is encrypted we do not want to expose it unnecessarily.

2023-10-11 00:29 UTC, theGaryLarson commented on src/user/dto/create-user.dto.ts
> +  password: string;
Here do not include password. This dto minimally needs informationi for an admin to set an user's role.
Email and password is used in user auth.

2023-10-12 17:45 UTC, Ali-7s commented on src/user/dto/create-user.dto.ts
> +  password: string;
Removed the password field

2023-10-12 20:22 UTC, taylorpapke commented
@theGaryLarson I'm noticing that on PR's where another push is made, CI is running Continuous-Integration / build-and-test and not completing. @Ali-7s I'm pretty sure if this PR is closed and reopened, it will run CI (on pull-request) / Continuous-Integration / build-and-test (pull_request) and complete. Perhaps something to look into more.

2023-10-12 20:24 UTC, taylorpapke commented
Sorry, I accidentally closed with comment rather than just commenting!

2023-10-15 17:00 UTC, Seiyaroo commented on src/user/dto/create-user.dto.ts
> +  IsAlpha,
I'm not familiar with the isAlpha, am assuming that means Alphanumeric?

2023-10-15 17:00 UTC, Seiyaroo submitted a review, later dismissed
Based on the current settings I feel this is approvable but we have some outstanding changes maybe it looks like?

2023-10-17 00:06 UTC, theGaryLarson approved these changes
Looks good @Ali-7s

2023-10-17 00:06 UTC, theGaryLarson commented on src/user/dto/create-user.dto.ts
> +  name: string;
Must be equal to or longer than 2 letters. The 2 is inclusive.

2023-10-17 00:07 UTC, theGaryLarson requested changes
Just the message on min length of name needs a bit of adjustment. Looks good!

2023-10-18 03:18 UTC, Seiyaroo approved these changes
I believe this was the only standing issue from Gary's request. With that resolved, this LGTM.

2023-10-18 23:14 UTC, Seiyaroo approved these changes
LGTM, I think the only requested change was the "Equal or greater than" change.

2023-10-24 02:25 UTC, theGaryLarson submitted a review, later dismissed
Looks good

2023-10-24 02:39 UTC, merged