Updated schema, dto, and model to include first name and last name
SeattleColleges/nsc-events-nestjs pull request #73
Opened 2024-01-28 08:22 UTC by intisarosman1

Resolves #72 

I updated all schemas, dtos, and models to include first name and last name, so that the toast message on the frontend could correctly reference first name.

Related to this [User Story](https://github.com/SeattleColleges/nsc-events-android/issues/188)

2024-01-28 15:43 UTC, brinkbrink requested changes
Hi @intisarosman1 thank you for asking for clarification here. You will need to fix the tests, it looks like that may be why the checks are still failing. There is also a suggestion from CodeFactor if you click the "Details" link next to it. Please reach out if you need any support fixing the tests to match the changes you've made.

2024-01-28 15:45 UTC, brinkbrink commented
Actually, looking closer, the tests aren't really the issue. Click the Details link to the failing check to see why. And again, let us know if it's not making sense to you.

2024-01-29 06:58 UTC, heosman approved these changes

2024-01-30 08:55 UTC, taylorpapke approved these changes
Looks good. I was able to sign up a user with the UI. I also ran npm run test user.service.spec.ts and it is passing all tests:
<img width="474" alt="Screenshot 2024-01-30 at 12 54 13 AM" src="https://github.com/SeattleColleges/nsc-events-nestjs/assets/94101953/95ae0ad2-91b7-4322-8586-e22d6107263f">

2024-01-30 09:10 UTC, merged