nsc-events-nestjs-5-8-event-controller-service-model-injection-creation
SeattleColleges/nsc-events-nestjs pull request #9
Opened 2023-08-20 22:41 UTC by taylorpapke

resolves: https://github.com/SeattleColleges/nsc-events-nestjs/issues/8

Created an event schema, service class-model injection, and controller.
This is a simple scalable CRUD application using NestJS Mongoose - connected to the local MongoDB instance.
To test the CRUD you will need to create a .env file with the variables below:

MONGODB_URI=<'your mongodb URI with username and password'>

Test add event (POST):
<img width="720" alt="Screenshot 2023-08-20 at 2 58 15 PM" src="https://github.com/SeattleColleges/nsc-events-nestjs/assets/94101953/20125982-aa17-4e7e-9c35-5e9d12dc32ea">
Test find event by id (GET):
<img width="720" alt="Screenshot 2023-08-20 at 2 58 47 PM" src="https://github.com/SeattleColleges/nsc-events-nestjs/assets/94101953/01344c2c-90f7-4b86-bf26-333e72684706">
Test view all events (GET):
<img width="714" alt="Screenshot 2023-08-20 at 2 59 55 PM" src="https://github.com/SeattleColleges/nsc-events-nestjs/assets/94101953/01a7bb19-34cb-418d-ae8c-2d85c4ebf23c">
Test update event (PATCH):
<img width="725" alt="Screenshot 2023-08-20 at 3 03 14 PM" src="https://github.com/SeattleColleges/nsc-events-nestjs/assets/94101953/421f881b-db45-45df-96d6-619534f39e46">
Test view updated event by id (GET):
<img width="719" alt="Screenshot 2023-08-20 at 3 03 41 PM" src="https://github.com/SeattleColleges/nsc-events-nestjs/assets/94101953/631c0b70-2223-490a-aed1-bfd2f9974e77">

2023-08-22 21:36 UTC, Robel-003 approved these changes
Overall this looks great! Ran it locally using postman and mongoDB. Each request is returning the expected result.

2023-08-22 21:36 UTC, Robel-003 commented on src/activity/types/activity.model.ts
> +export const ActivitySchema = new Schema<ActivityDocument>({
Some of the fields that are required can probably be optional depending on if the user has the data readily available. 
For postman, the eventDate requires a date requires an entry like ("2022-06-05T00:00:00Z"). When data is being passed to database from frontend, we could convert the date/time to that format

2023-08-22 21:36 UTC, Robel-003 commented on src/activity/services/activity/activity.service.ts
> +  async addEvent(
This might be minor and or somewhat unnecessary but in addition to the displaying the add/updated event, a message to signify that an event has been added/updated could probably be helpful. And this might be something for the frontend side of things

2023-08-22 21:36 UTC, Robel-003 commented on src/activity/controllers/activity/activity.controller.ts
> +  @Patch('update/:id')
We could probably add some validation checks here when updating an event. Currently when a wrong or incorrect id is entered, a 505 server error is shown. We could add a better error signifying what the error is about

2023-08-24 17:20 UTC, theGaryLarson commented on src/activity/controllers/activity/activity.controller.ts
> +  @Patch('update/:id')
@Robel-003 Great feedback. Could you document those suggestions so we can hand them over to PMs as a list of todos for students on MVP 2? Then we can hand them off to the PMs to consolidate and share with BC.

2023-08-24 17:26 UTC, theGaryLarson requested changes
Looks good! I echo Robel's suggestions but think it would be better left as tasks for students in the fall. @taylorpapke Also,  Socket security flagged a change to mongoose in the package.json. Please update your package json to use the version originally in use. `7.4.2`

2023-08-24 18:11 UTC, brinkbrink commented on src/activity/controllers/activity/activity.controller.ts
> +  @Patch('update/:id')
I just added these suggestions to the "Fall & Beyond" section of [Belinda's Informal Plan](https://www.notion.so/belindas-closet/Informal-Plan-Schedule-22e303af32ac421eb7d3d4c896de4ad6?pvs=4).

2023-08-24 18:11 UTC, brinkbrink commented on src/activity/controllers/activity/activity.controller.ts
> +  @Patch('update/:id')
Although I know this is not for Belinda's, but it will be useful in our overall plan and Belinda's plan is basically the overall plan at this point.

2023-08-31 05:09 UTC, theGaryLarson approved these changes
LGTM! Thank you!

2023-08-31 05:11 UTC, merged